export enum ExerciseType {
  WarmUp = 1,
  Gym = 2,
  Circuit = 3,
  Isometric = 4,
  Plyometric = 5,
  Sprint = 6,
  Drill = 7,
}

export interface Exercise {
  id: number
  name: string
  order: number
  exercise_type: ExerciseType
  // Basic parameters
  sets: number
  reps: string
  weight?: string
  rest_time?: number // in seconds
  rpe?: number
  // Advanced parameters
  tempo?: string // e.g., "3-0-1-0"
  distance?: number // in meters
  duration?: number // in seconds
  power?: number // in watts
  velocity?: number // in m/s
  effort?: string // e.g., "moderate", "hard"
  height?: number // in cm
  resistance?: string // e.g., "light band", "heavy band"
  performing_time?: number // in seconds
  notes?: string
  superset_group?: string // for grouping exercises in supersets
}

export interface Session {
  id: number
  name: string
  type: "speed" | "strength" | "endurance" | "recovery" | "technique"
  duration: number
  exercises: Exercise[]
  volume: number
  intensity: number
  notes?: string
}

export interface Microcycle {
  id: number
  name: string
  weekNumber: number
  startDate: string
  endDate: string
  sessions: Session[]
  volume: number
  intensity: number
  isDeload: boolean
  focus: string
}

export interface Mesocycle {
  id: number
  name: string
  phase: "GPP" | "SPP" | "Taper" | "Competition"
  startDate: string
  endDate: string
  microcycles: Microcycle[]
  color: string
  description: string
  totalSessions: number
  avgVolume: number
  avgIntensity: number
}

export interface RaceAnchor {
  id: number
  name: string
  date: string
  type: "primary" | "secondary"
  event: string
}

export interface TrainingPlan {
  id: number
  name: string
  startDate: string
  endDate: string
  mesocycles: Mesocycle[]
  raceAnchors: RaceAnchor[]
  status: "active" | "draft" | "completed"
}

// Enhanced sample exercises library with full parameters and exercise types
const sampleExercises = {
  speed: [
    {
      id: 1,
      name: "Block Starts",
      exercise_type: ExerciseType.Sprint,
      sets: 6,
      reps: "1",
      rest_time: 180,
      rpe: 8,
      distance: 30,
      velocity: 9.5,
      effort: "maximal",
    },
    {
      id: 2,
      name: "Flying 30m",
      exercise_type: ExerciseType.Sprint,
      sets: 4,
      reps: "1",
      rest_time: 300,
      rpe: 9,
      distance: 30,
      velocity: 10.2,
      effort: "maximal",
    },
    {
      id: 3,
      name: "Acceleration Runs",
      exercise_type: ExerciseType.Sprint,
      sets: 5,
      reps: "1",
      rest_time: 240,
      rpe: 8,
      distance: 40,
      velocity: 8.8,
      effort: "near-maximal",
    },
    {
      id: 4,
      name: "Speed Endurance",
      exercise_type: ExerciseType.Sprint,
      sets: 3,
      reps: "1",
      rest_time: 480,
      rpe: 9,
      distance: 150,
      velocity: 7.5,
      effort: "hard",
    },
    {
      id: 5,
      name: "Sled Push",
      exercise_type: ExerciseType.Sprint,
      sets: 4,
      reps: "1",
      rest_time: 180,
      rpe: 8,
      distance: 20,
      resistance: "50% BW",
      effort: "maximal",
    },
    {
      id: 6,
      name: "Resisted Sprints",
      exercise_type: ExerciseType.Sprint,
      sets: 5,
      reps: "1",
      rest_time: 240,
      rpe: 7,
      distance: 30,
      resistance: "light band",
      velocity: 7.2,
    },
  ],
  strength: [
    {
      id: 7,
      name: "Back Squat",
      exercise_type: ExerciseType.Gym,
      sets: 4,
      reps: "5",
      weight: "85% 1RM",
      rest_time: 180,
      rpe: 8,
      tempo: "3-0-1-0",
      performing_time: 20,
    },
    {
      id: 8,
      name: "Romanian Deadlift",
      exercise_type: ExerciseType.Gym,
      sets: 3,
      reps: "8",
      weight: "75% 1RM",
      rest_time: 120,
      rpe: 7,
      tempo: "3-1-1-0",
      performing_time: 24,
    },
    {
      id: 9,
      name: "Nordic Hamstring",
      exercise_type: ExerciseType.Gym,
      sets: 3,
      reps: "6",
      rest_time: 120,
      rpe: 8,
      tempo: "4-0-1-0",
      weight: "BW",
      performing_time: 30,
    },
    {
      id: 10,
      name: "Single Leg Squat",
      exercise_type: ExerciseType.Gym,
      sets: 3,
      reps: "8",
      weight: "BW",
      rest_time: 90,
      rpe: 7,
      tempo: "2-0-1-0",
    },
    {
      id: 11,
      name: "Bench Press",
      exercise_type: ExerciseType.Gym,
      sets: 4,
      reps: "6",
      weight: "80% 1RM",
      rest_time: 180,
      rpe: 8,
      tempo: "2-0-1-0",
      performing_time: 18,
    },
    {
      id: 12,
      name: "Pull-ups",
      exercise_type: ExerciseType.Gym,
      sets: 3,
      reps: "8",
      weight: "BW + 10kg",
      rest_time: 120,
      rpe: 7,
      tempo: "2-0-1-0",
    },
    {
      id: 13,
      name: "Box Jump",
      exercise_type: ExerciseType.Plyometric,
      sets: 4,
      reps: "5",
      rest_time: 120,
      rpe: 7,
      height: 60,
      power: 1200,
      effort: "explosive",
    },
    {
      id: 14,
      name: "Trap Bar Deadlift",
      exercise_type: ExerciseType.Gym,
      sets: 4,
      reps: "5",
      weight: "85% 1RM",
      rest_time: 180,
      rpe: 8,
      tempo: "1-0-1-0",
      power: 800,
    },
  ],
  endurance: [
    {
      id: 15,
      name: "Tempo Runs",
      exercise_type: ExerciseType.Sprint,
      sets: 4,
      reps: "1",
      rest_time: 120,
      rpe: 6,
      distance: 200,
      velocity: 5.5,
      effort: "moderate",
      duration: 36,
    },
    {
      id: 16,
      name: "Extensive Tempo",
      exercise_type: ExerciseType.Sprint,
      sets: 6,
      reps: "1",
      rest_time: 60,
      rpe: 5,
      distance: 100,
      velocity: 5.0,
      effort: "easy",
      duration: 20,
    },
    {
      id: 17,
      name: "Continuous Run",
      exercise_type: ExerciseType.Sprint,
      sets: 1,
      reps: "1",
      rpe: 5,
      distance: 3000,
      duration: 1200,
      velocity: 2.5,
      effort: "easy",
    },
    {
      id: 18,
      name: "Fartlek",
      exercise_type: ExerciseType.Sprint,
      sets: 1,
      reps: "1",
      rpe: 6,
      distance: 2000,
      duration: 600,
      effort: "varied",
    },
  ],
  recovery: [
    {
      id: 19,
      name: "Light Jog",
      exercise_type: ExerciseType.WarmUp,
      sets: 1,
      reps: "1",
      rpe: 3,
      distance: 1500,
      duration: 900,
      velocity: 1.7,
      effort: "very easy",
    },
    {
      id: 20,
      name: "Dynamic Stretching",
      exercise_type: ExerciseType.WarmUp,
      sets: 2,
      reps: "10",
      rpe: 2,
      duration: 600,
      effort: "light",
    },
    {
      id: 21,
      name: "Foam Rolling",
      exercise_type: ExerciseType.WarmUp,
      sets: 1,
      reps: "1",
      rpe: 2,
      duration: 900,
      effort: "light",
    },
    {
      id: 22,
      name: "Yoga Flow",
      exercise_type: ExerciseType.WarmUp,
      sets: 1,
      reps: "1",
      rpe: 3,
      duration: 1800,
      effort: "light",
    },
  ],
  technique: [
    {
      id: 23,
      name: "A-Skips",
      exercise_type: ExerciseType.Drill,
      sets: 3,
      reps: "1",
      rest_time: 90,
      rpe: 4,
      distance: 30,
      effort: "controlled",
    },
    {
      id: 24,
      name: "B-Skips",
      exercise_type: ExerciseType.Drill,
      sets: 3,
      reps: "1",
      rest_time: 90,
      rpe: 4,
      distance: 30,
      effort: "controlled",
    },
    {
      id: 25,
      name: "Wickets",
      exercise_type: ExerciseType.Drill,
      sets: 4,
      reps: "1",
      rest_time: 120,
      rpe: 5,
      distance: 20,
      height: 30,
      effort: "controlled",
    },
    {
      id: 26,
      name: "High Knees",
      exercise_type: ExerciseType.Drill,
      sets: 3,
      reps: "1",
      rest_time: 90,
      rpe: 4,
      distance: 30,
      effort: "controlled",
    },
    {
      id: 27,
      name: "Butt Kicks",
      exercise_type: ExerciseType.Drill,
      sets: 3,
      reps: "1",
      rest_time: 90,
      rpe: 4,
      distance: 30,
      effort: "controlled",
    },
  ],
  plyometric: [
    {
      id: 28,
      name: "Depth Jumps",
      exercise_type: ExerciseType.Plyometric,
      sets: 4,
      reps: "5",
      rest_time: 180,
      rpe: 7,
      height: 45,
      power: 1500,
      effort: "explosive",
    },
    {
      id: 29,
      name: "Bounding",
      exercise_type: ExerciseType.Plyometric,
      sets: 4,
      reps: "10",
      rest_time: 120,
      rpe: 6,
      distance: 30,
      effort: "explosive",
    },
    {
      id: 30,
      name: "Single Leg Hops",
      exercise_type: ExerciseType.Plyometric,
      sets: 3,
      reps: "8",
      rest_time: 90,
      rpe: 6,
      distance: 20,
      effort: "explosive",
    },
  ],
  core: [
    {
      id: 31,
      name: "Plank",
      exercise_type: ExerciseType.Isometric,
      sets: 3,
      reps: "1",
      rest_time: 60,
      rpe: 5,
      duration: 60,
      effort: "moderate",
    },
    {
      id: 32,
      name: "Russian Twists",
      exercise_type: ExerciseType.Gym,
      sets: 3,
      reps: "20",
      rest_time: 60,
      rpe: 6,
      weight: "10kg",
      tempo: "1-0-1-0",
    },
    {
      id: 33,
      name: "Dead Bug",
      exercise_type: ExerciseType.Gym,
      sets: 3,
      reps: "12",
      rest_time: 60,
      rpe: 5,
      tempo: "2-1-2-1",
    },
  ],
}

// Generate sample sessions with 10-12 exercises each
function createSession(
  id: number,
  name: string,
  type: Session["type"],
  exerciseList: Array<Partial<Exercise>>,
  volume: number,
  intensity: number,
): Session {
  const exercises = exerciseList.map(
    (ex, index) =>
      ({
        ...ex,
        id: ex.id || id * 100 + index,
        order: index + 1,
        name: ex.name || "Exercise",
        exercise_type: ex.exercise_type || ExerciseType.Gym,
        sets: ex.sets || 3,
        reps: ex.reps || "10",
      }) as Exercise,
  )

  return {
    id,
    name,
    type,
    duration: 90,
    exercises,
    volume,
    intensity,
  }
}

const phaseColors = [
  "#10b981",
  "#14b8a6",
  "#06b6d4",
  "#0ea5e9",
  "#3b82f6",
  "#6366f1",
  "#8b5cf6",
  "#a855f7",
  "#d946ef",
  "#ec4899",
  "#f43f5e",
  "#ef4444",
  "#f97316",
  "#f59e0b",
  "#eab308",
  "#84cc16",
]

// Sample training plan data with comprehensive sessions
export const samplePlan: TrainingPlan = {
  id: 1,
  name: "Fall Championship Season 2025",
  startDate: "2025-08-04",
  endDate: "2025-10-12",
  status: "active",
  raceAnchors: [
    {
      id: 1,
      name: "State Championships",
      date: "2025-10-12",
      type: "primary",
      event: "100m, 200m",
    },
    {
      id: 2,
      name: "Tune-up Meet",
      date: "2025-09-28",
      type: "secondary",
      event: "100m",
    },
  ],
  mesocycles: [
    {
      id: 1,
      name: "General Preparation Phase",
      phase: "GPP",
      startDate: "2025-08-04",
      endDate: "2025-08-24",
      color: phaseColors[0], // Using simplified color palette
      description: "Building aerobic base and general strength foundation",
      totalSessions: 9,
      avgVolume: 75,
      avgIntensity: 6.5,
      microcycles: [
        {
          id: 1,
          name: "Week 1",
          weekNumber: 1,
          startDate: "2025-08-04",
          endDate: "2025-08-10",
          volume: 70,
          intensity: 6.0,
          isDeload: false,
          focus: "Base Building",
          sessions: [
            createSession(
              1,
              "Monday - Tempo & Strength",
              "endurance",
              [
                { ...sampleExercises.technique[0], superset_group: "warmup" },
                { ...sampleExercises.technique[1], superset_group: "warmup" },
                { ...sampleExercises.endurance[0] },
                { ...sampleExercises.endurance[1] },
                { ...sampleExercises.strength[0], superset_group: "A" },
                { ...sampleExercises.strength[1], superset_group: "A" },
                { ...sampleExercises.strength[2], superset_group: "B" },
                { ...sampleExercises.strength[3], superset_group: "B" },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.recovery[1] },
              ],
              70,
              6,
            ),
            createSession(
              2,
              "Wednesday - Technique & Speed",
              "technique",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.technique[1] },
                { ...sampleExercises.technique[3] },
                { ...sampleExercises.technique[4] },
                { ...sampleExercises.speed[0] },
                { ...sampleExercises.speed[2] },
                { ...sampleExercises.plyometric[1] },
                { ...sampleExercises.plyometric[2] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              65,
              6,
            ),
            createSession(
              3,
              "Friday - Endurance & Recovery",
              "endurance",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.endurance[1] },
                { ...sampleExercises.endurance[0] },
                { ...sampleExercises.endurance[3] },
                { ...sampleExercises.strength[3] },
                { ...sampleExercises.strength[2] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.recovery[0] },
                { ...sampleExercises.recovery[1] },
              ],
              60,
              5,
            ),
          ],
        },
        {
          id: 2,
          name: "Week 2",
          weekNumber: 2,
          startDate: "2025-08-11",
          endDate: "2025-08-17",
          volume: 80,
          intensity: 7.0,
          isDeload: false,
          focus: "Volume Increase",
          sessions: [
            createSession(
              4,
              "Monday - Speed & Strength",
              "speed",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.technique[1] },
                { ...sampleExercises.speed[0] },
                { ...sampleExercises.speed[2] },
                { ...sampleExercises.speed[5] },
                { ...sampleExercises.strength[0], superset_group: "A" },
                { ...sampleExercises.strength[4], superset_group: "A" },
                { ...sampleExercises.strength[6], superset_group: "B" },
                { ...sampleExercises.plyometric[0], superset_group: "B" },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              80,
              7,
            ),
            createSession(
              5,
              "Wednesday - Tempo",
              "endurance",
              [
                { ...sampleExercises.technique[3] },
                { ...sampleExercises.technique[4] },
                { ...sampleExercises.endurance[0] },
                { ...sampleExercises.endurance[1] },
                { ...sampleExercises.endurance[3] },
                { ...sampleExercises.strength[3] },
                { ...sampleExercises.strength[2] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              75,
              6,
            ),
            createSession(
              6,
              "Friday - Strength Focus",
              "strength",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.technique[1] },
                { ...sampleExercises.strength[0] },
                { ...sampleExercises.strength[7] },
                { ...sampleExercises.strength[4] },
                { ...sampleExercises.strength[5] },
                { ...sampleExercises.strength[1] },
                { ...sampleExercises.strength[2] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              85,
              8,
            ),
          ],
        },
        {
          id: 3,
          name: "Week 3",
          weekNumber: 3,
          startDate: "2025-08-18",
          endDate: "2025-08-24",
          volume: 60,
          intensity: 5.5,
          isDeload: true,
          focus: "Recovery Week",
          sessions: [
            createSession(
              7,
              "Monday - Light Tempo",
              "recovery",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.technique[1] },
                { ...sampleExercises.recovery[0] },
                { ...sampleExercises.recovery[1] },
                { ...sampleExercises.endurance[1] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.recovery[2] },
              ],
              50,
              4,
            ),
            createSession(
              8,
              "Wednesday - Technique",
              "technique",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.technique[1] },
                { ...sampleExercises.technique[2] },
                { ...sampleExercises.technique[3] },
                { ...sampleExercises.technique[4] },
                { ...sampleExercises.plyometric[2] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              60,
              5,
            ),
            createSession(
              9,
              "Friday - Recovery",
              "recovery",
              [
                { ...sampleExercises.recovery[0] },
                { ...sampleExercises.recovery[1] },
                { ...sampleExercises.recovery[3] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.recovery[2] },
              ],
              40,
              4,
            ),
          ],
        },
      ],
    },
    {
      id: 2,
      name: "Specific Preparation Phase",
      phase: "SPP",
      startDate: "2025-08-25",
      endDate: "2025-09-21",
      color: phaseColors[4], // Using simplified color palette
      description: "Developing race-specific speed and power",
      totalSessions: 12,
      avgVolume: 85,
      avgIntensity: 7.8,
      microcycles: [
        {
          id: 4,
          name: "Week 4",
          weekNumber: 4,
          startDate: "2025-08-25",
          endDate: "2025-08-31",
          volume: 85,
          intensity: 7.5,
          isDeload: false,
          focus: "Speed Development",
          sessions: [
            createSession(
              10,
              "Monday - Max Velocity",
              "speed",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.technique[1] },
                { ...sampleExercises.speed[1] },
                { ...sampleExercises.speed[2] },
                { ...sampleExercises.speed[3] },
                { ...sampleExercises.plyometric[0] },
                { ...sampleExercises.plyometric[1] },
                { ...sampleExercises.strength[6] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              85,
              8,
            ),
            createSession(
              11,
              "Wednesday - Strength",
              "strength",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.strength[0] },
                { ...sampleExercises.strength[7] },
                { ...sampleExercises.strength[4] },
                { ...sampleExercises.strength[5] },
                { ...sampleExercises.strength[1] },
                { ...sampleExercises.strength[2] },
                { ...sampleExercises.strength[3] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              90,
              8,
            ),
            createSession(
              12,
              "Friday - Speed Endurance",
              "speed",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.technique[1] },
                { ...sampleExercises.speed[3] },
                { ...sampleExercises.endurance[0] },
                { ...sampleExercises.endurance[3] },
                { ...sampleExercises.plyometric[1] },
                { ...sampleExercises.plyometric[2] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              80,
              7,
            ),
          ],
        },
        {
          id: 5,
          name: "Week 5",
          weekNumber: 5,
          startDate: "2025-09-01",
          endDate: "2025-09-07",
          volume: 90,
          intensity: 8.0,
          isDeload: false,
          focus: "Peak Volume",
          sessions: [
            createSession(
              13,
              "Monday - Acceleration",
              "speed",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.speed[0] },
                { ...sampleExercises.speed[2] },
                { ...sampleExercises.speed[5] },
                { ...sampleExercises.plyometric[1] },
                { ...sampleExercises.plyometric[2] },
                { ...sampleExercises.strength[6] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              90,
              8,
            ),
            createSession(
              14,
              "Wednesday - Power",
              "strength",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.strength[0] },
                { ...sampleExercises.strength[7] },
                { ...sampleExercises.strength[4] },
                { ...sampleExercises.strength[5] },
                { ...sampleExercises.strength[1] },
                { ...sampleExercises.strength[2] },
                { ...sampleExercises.strength[3] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              95,
              8,
            ),
            createSession(
              15,
              "Thursday - Tempo",
              "endurance",
              [
                { ...sampleExercises.endurance[0] },
                { ...sampleExercises.endurance[1] },
                { ...sampleExercises.endurance[3] },
                { ...sampleExercises.strength[3] },
                { ...sampleExercises.strength[2] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.recovery[0] },
                { ...sampleExercises.recovery[1] },
              ],
              70,
              6,
            ),
            createSession(
              16,
              "Saturday - Speed Work",
              "speed",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.speed[1] },
                { ...sampleExercises.speed[3] },
                { ...sampleExercises.speed[5] },
                { ...sampleExercises.plyometric[1] },
                { ...sampleExercises.plyometric[2] },
                { ...sampleExercises.strength[6] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              85,
              8,
            ),
          ],
        },
        {
          id: 6,
          name: "Week 6",
          weekNumber: 6,
          startDate: "2025-09-08",
          endDate: "2025-09-14",
          volume: 85,
          intensity: 8.0,
          isDeload: false,
          focus: "Race Pace",
          sessions: [
            createSession(
              17,
              "Monday - Race Pace",
              "speed",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.speed[1] },
                { ...sampleExercises.speed[3] },
                { ...sampleExercises.speed[5] },
                { ...sampleExercises.plyometric[1] },
                { ...sampleExercises.plyometric[2] },
                { ...sampleExercises.strength[6] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              85,
              8,
            ),
            createSession(
              18,
              "Wednesday - Maintenance",
              "strength",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.strength[0] },
                { ...sampleExercises.strength[7] },
                { ...sampleExercises.strength[4] },
                { ...sampleExercises.strength[5] },
                { ...sampleExercises.strength[1] },
                { ...sampleExercises.strength[2] },
                { ...sampleExercises.strength[3] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              80,
              7,
            ),
            createSession(
              19,
              "Friday - Speed Endurance",
              "speed",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.speed[3] },
                { ...sampleExercises.endurance[0] },
                { ...sampleExercises.endurance[3] },
                { ...sampleExercises.plyometric[1] },
                { ...sampleExercises.plyometric[2] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              75,
              8,
            ),
          ],
        },
        {
          id: 7,
          name: "Week 7",
          weekNumber: 7,
          startDate: "2025-09-15",
          endDate: "2025-09-21",
          volume: 70,
          intensity: 7.0,
          isDeload: true,
          focus: "Recovery",
          sessions: [
            createSession(
              20,
              "Monday - Light Speed",
              "technique",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.technique[1] },
                { ...sampleExercises.speed[0] },
                { ...sampleExercises.speed[2] },
                { ...sampleExercises.speed[5] },
                { ...sampleExercises.plyometric[1] },
                { ...sampleExercises.plyometric[2] },
                { ...sampleExercises.strength[6] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              60,
              6,
            ),
            createSession(
              21,
              "Wednesday - Recovery",
              "recovery",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.recovery[0] },
                { ...sampleExercises.recovery[1] },
                { ...sampleExercises.recovery[3] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              50,
              5,
            ),
            createSession(
              22,
              "Friday - Tempo",
              "endurance",
              [
                { ...sampleExercises.endurance[1] },
                { ...sampleExercises.endurance[0] },
                { ...sampleExercises.endurance[3] },
                { ...sampleExercises.strength[3] },
                { ...sampleExercises.strength[2] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.recovery[0] },
                { ...sampleExercises.recovery[1] },
              ],
              55,
              6,
            ),
          ],
        },
      ],
    },
    {
      id: 3,
      name: "Taper Phase",
      phase: "Taper",
      startDate: "2025-09-22",
      endDate: "2025-10-05",
      color: phaseColors[13], // Using simplified color palette
      description: "Reducing volume while maintaining intensity",
      totalSessions: 6,
      avgVolume: 50,
      avgIntensity: 8.5,
      microcycles: [
        {
          id: 8,
          name: "Week 8",
          weekNumber: 8,
          startDate: "2025-09-22",
          endDate: "2025-09-28",
          volume: 60,
          intensity: 8.5,
          isDeload: false,
          focus: "Taper Start",
          sessions: [
            createSession(
              23,
              "Monday - Quality Speed",
              "speed",
              [
                { ...sampleExercises.speed[1] },
                { ...sampleExercises.speed[2] },
                { ...sampleExercises.speed[3] },
                { ...sampleExercises.plyometric[0] },
                { ...sampleExercises.plyometric[1] },
                { ...sampleExercises.strength[6] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              60,
              9,
            ),
            createSession(
              24,
              "Wednesday - Light Strength",
              "strength",
              [
                { ...sampleExercises.strength[0] },
                { ...sampleExercises.strength[7] },
                { ...sampleExercises.strength[4] },
                { ...sampleExercises.strength[5] },
                { ...sampleExercises.strength[1] },
                { ...sampleExercises.strength[2] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              50,
              7,
            ),
            createSession(
              25,
              "Saturday - Tune-up Race",
              "speed",
              [{ id: 2500, name: "Tune-up Meet", exercise_type: ExerciseType.Sprint, sets: 1, reps: "100m", rpe: 9 }],
              70,
              9,
            ),
          ],
        },
        {
          id: 9,
          name: "Week 9",
          weekNumber: 9,
          startDate: "2025-09-29",
          endDate: "2025-10-05",
          volume: 40,
          intensity: 8.5,
          isDeload: false,
          focus: "Final Taper",
          sessions: [
            createSession(
              26,
              "Monday - Short Speed",
              "speed",
              [
                { ...sampleExercises.speed[0] },
                { ...sampleExercises.speed[2] },
                { ...sampleExercises.speed[5] },
                { ...sampleExercises.plyometric[1] },
                { ...sampleExercises.plyometric[2] },
                { ...sampleExercises.strength[6] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              40,
              8,
            ),
            createSession(
              27,
              "Wednesday - Activation",
              "technique",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.technique[1] },
                { ...sampleExercises.speed[0] },
                { ...sampleExercises.speed[2] },
                { ...sampleExercises.speed[5] },
                { ...sampleExercises.plyometric[1] },
                { ...sampleExercises.plyometric[2] },
                { ...sampleExercises.strength[6] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              30,
              7,
            ),
            createSession(
              28,
              "Friday - Pre-race Prep",
              "technique",
              [
                { ...sampleExercises.technique[2] },
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.technique[1] },
                { ...sampleExercises.speed[0] },
                { ...sampleExercises.speed[2] },
                { ...sampleExercises.plyometric[1] },
                { ...sampleExercises.plyometric[2] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              25,
              6,
            ),
          ],
        },
      ],
    },
    {
      id: 4,
      name: "Competition Phase",
      phase: "Competition",
      startDate: "2025-10-06",
      endDate: "2025-10-12",
      color: phaseColors[11], // Using simplified color palette
      description: "Peak performance and competition",
      totalSessions: 2,
      avgVolume: 30,
      avgIntensity: 9.0,
      microcycles: [
        {
          id: 10,
          name: "Week 10",
          weekNumber: 10,
          startDate: "2025-10-06",
          endDate: "2025-10-12",
          volume: 30,
          intensity: 9.0,
          isDeload: false,
          focus: "Competition",
          sessions: [
            createSession(
              29,
              "Monday - Activation",
              "technique",
              [
                { ...sampleExercises.technique[0] },
                { ...sampleExercises.technique[1] },
                { ...sampleExercises.speed[0] },
                { ...sampleExercises.speed[2] },
                { ...sampleExercises.plyometric[1] },
                { ...sampleExercises.plyometric[2] },
                { ...sampleExercises.core[0] },
                { ...sampleExercises.core[1] },
                { ...sampleExercises.core[2] },
                { ...sampleExercises.recovery[1] },
              ],
              20,
              6,
            ),
            createSession(
              30,
              "Saturday - State Championships",
              "speed",
              [
                {
                  id: 3000,
                  name: "State Championships",
                  exercise_type: ExerciseType.Sprint,
                  sets: 1,
                  reps: "100m, 200m",
                  rpe: 10,
                },
              ],
              40,
              10,
            ),
          ],
        },
      ],
    },
  ],
}
