export { default as Hero } from './hero'
export { default as Features } from './features'
export { default as Pricing } from './pricing'
export { default as About } from './about'
export { default as Testimonials } from './testimonials'
export { default as CTA } from './cta'
export { default as FAQ } from './faq' 