/**
 * Root Layout Component
 * 
 * This is the top-level layout component that wraps all pages in the application.
 * It provides common structure, styling, and context providers for the entire app.
 * 
 * Features:
 * - Global CSS imports
 * - Font configuration (Inter from Google Fonts)
 * - Authentication context provider
 * - Responsive layout structure
 * - Common header component
 */

import "./css/style.css"

import { Inter } from "next/font/google"

import { AuthProvider } from "../context/authContext"
import Header from "../components/ui/header"

// Configure the Inter font with Latin character subset
const inter = Inter({ subsets: ["latin"] })

/**
 * Metadata configuration for the application
 * This information is used by Next.js for SEO and document head
 */
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

/**
 * Root Layout Component
 * 
 * @param {Object} props - Component props
 * @param {React.ReactNode} props.children - Child components to be rendered within the layout
 * @returns {React.JSX.Element} The root layout structure
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-inter antialiased bg-gray-50 text-gray-900 tracking-tight`}>
        {/* AuthProvider wraps the app to provide authentication context */}
        <AuthProvider>
          {/* Main layout structure with flex column and minimum height */}
          <div className="flex flex-col min-h-screen overflow-hidden">
            {/* Global header component */}
            <Header />
            {/* Main content area with top padding for header */}
            <main className="grow pt-20">
              {children}
            </main>
          </div>
        </AuthProvider>
      </body>
    </html>
  )
}
