export { AISessionAssistantDemo } from './AISessionAssistantDemo'
export { ChatDrawer } from './ChatDrawer'
export { ApprovalBanner } from './ApprovalBanner'
export { ExerciseCardInline, NewExerciseCard } from './ExerciseCardInline'
export { SupersetContainer } from './SupersetContainer'
// Legacy components (can be removed)
export { ReviewChangesSheet } from './ReviewChangesSheet'
export { ChangeDetailSheet } from './ChangeDetailSheet'
export { PendingChangesBanner } from './PendingChangesBanner'
export { MockSessionCard } from './MockSessionCard'
export * from './types'
export * from './mock-data'
