-- Track ENABLE ROW LEVEL SECURITY for all core tables.
-- These already have RLS enabled in the live database but were not tracked in migrations.
-- This ensures reproducibility on db reset.

ALTER TABLE IF EXISTS public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.athletes ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.coaches ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.athlete_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.athlete_group_histories ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.athlete_cycles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.athlete_personal_bests ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.macrocycles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.mesocycles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.microcycles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.session_plans ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.session_plan_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.session_plan_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.workout_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.workout_log_exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.workout_log_sets ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.exercises ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.exercise_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.exercise_tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.races ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tags ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.units ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ai_memories ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.knowledge_base_articles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.knowledge_base_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.push_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.reminder_preferences ENABLE ROW LEVEL SECURITY;
